### ISSUE TITLE
Hex colors not working after the latest update

### ISSUE THREAD

**Issue by KahpotVanilla** [BukkitSmurf/LPC#11]
Yea, not working.
using 1.18.1
I had to revert back to the previous version and it works just fine

**Comment by BukkitSmurf** [comment]
Hey, could you explain your problem?

**Comment by KahpotVanilla** [comment]
> Hey, could you explain your problem?

Sure, after the update, my chat hexcolor shows only the hex codes, no colors

**Comment by BukkitSmurf** [comment]
Understand that. Could you send some screens of your setup e.g. config.yml, console if there are any errors, plugin list, link to your /lp editor?

**Comment by KahpotVanilla** [comment]
> Understand that. Could you send some screens of your setup e.g. config.yml, console if there are any errors, plugin list, link to your /lp editor?

No console errors at all, maybe it's because I installed Geyser, idk how to conflict it, but when I reverted back to the previous version, it was fixed.

**Comment by KahpotVanilla** [comment]
> Understand that. Could you send some screens of your setup e.g. config.yml, console if there are any errors, plugin list, link to your /lp editor?

I didn't changed the config much... only vault prefix and essentials nick placeholder, that's it

**Comment by BukkitSmurf** [comment]
So, could you show me your config file and plugins you use? I've just tested the issue and on my side everything works fine.

**Comment by KahpotVanilla** [comment]
alright, sure

**Comment by KahpotVanilla** [comment]
Plugins (26): Authy, BackToTheRoots, ChatManager, Essentials, EssentialsSpawn, FastAsyncWorldEdit, Geyser-Spigot, HolographicDisplays, LightAntiCheat, LPC, LuckPerms, Multiverse-Core, PlaceholderAPI, PLSecure,
[LPC version 3-4-1 config.yml.zip](https://github.com/BukkitSmurf/LPC/files/8193431/LPC.version.3-4-1.config.yml.zip)
 PlugManX, ProtocolLib, SkinsRestorer, Skywars, TAB, Vault, ViaBackwards, ViaRewind, ViaVersion, VoidGen, VoidSpawn, WorldGuard

**Comment by BukkitSmurf** [comment]
When you have Vault installed with ChatManager it holds chat formatting too. Make sure it's compatible with LPC and doesn't handle your chat format. From ChatManager Overview page on Spigot: https://i.imgur.com/jbyJ8xN.png

**Comment by BukkitSmurf** [comment]
And this is from GitHub wiki page of ChatManager: https://i.imgur.com/ncfJtHY.png (https://github.com/H1DD3NxN1NJA/ChatManager/wiki/Chat-Format). As you can see they are formating hex color codes like '#ff0000" and my plugin does "&#ff0000" instead. Maybe try disabling chat formatting in ChatManager's config and let LPC handle the chat formatting.

**Comment by KahpotVanilla** [comment]
> And this is from GitHub wiki page of ChatManager: https://i.imgur.com/ncfJtHY.png (https://github.com/H1DD3NxN1NJA/ChatManager/wiki/Chat-Format). As you can see they are formating hex color codes like '#ff0000" and my plugin does "&#ff0000" instead. Maybe try disabling chat formatting in ChatManager's config and let LPC handle the chat formatting.

I disabled it before updating in the config.yml

**Comment by KahpotVanilla** [comment]
> > And this is from GitHub wiki page of ChatManager: https://i.imgur.com/ncfJtHY.png (https://github.com/H1DD3NxN1NJA/ChatManager/wiki/Chat-Format). As you can see they are formating hex color codes like '#ff0000" and my plugin does "&#ff0000" instead. Maybe try disabling chat formatting in ChatManager's config and let LPC handle the chat formatting.
> 
> I disabled it before updating in the config.yml

But when I downgraded to the second version I got it worked

**Comment by LEP0N** [comment]
I have the same problem with last update. I use PlaceholderAPI javascript for color names in TAB and Chat. After update server on 1.18.2 (Pufferfish) and LPC to last version I get this bug (TAB works correctly).

LPC config: https://i.imgur.com/4BZuuG2.png
JavaScript Placeholder: https://i.imgur.com/ATRQZJ4.png
Bug: https://i.imgur.com/8yNuYYl.png

Plugins (40): AdvancedBan, AnnouncerPlus, ArmorStandAdjustor, AuthMe, Chunky, ChunkyBorder, ConsoleSpamFix, CoreProtect, CustomVillagerTrades, dynmap, EasyWhitelist, F3Name, FartherViewDistance, GSit, Harbor, InventoryRollbackPlus, ItemEdit, JoinFullServer*, LightAntiCheat, LPC, LuckPerms, MaterialDynmap*, MOTD, Multiverse-Core, OpenInv, PL-Hide, PlaceholderAPI, PlasmoVoice, PrivateMessages, ProtocolLib, ServerBackup, SimpleToolStats, SkinsRestorer, SurvivalInvisiframes, TAB, UltimateAutoRestart, UTitleAuth, Vault, VillagerModifications, WanderingTrades.

**Comment by BukkitSmurf** [comment]
I've recently updated the resource to version 3.4.3, it should work fine right now. Could you confirm that?

**Comment by BukkitSmurf** [comment]
Probably still not working, but please check. If it doesn't, we will revert to the previous version.

**Comment by BukkitSmurf** [comment]
I reverted the previous changes. New version 3.5.0 is out. Is it working correctly now?

**Comment by LEP0N** [comment]
Yes, it is working correctly now, thank you for your work!

**Comment by BukkitSmurf** [comment]
Great! Thanks for the fast response :)
