### ISSUE TITLE
[!uestion]

### ISSUE THREAD

**Issue by Arthuuurr** [BukkitSmurf/LPC#12]
Hello!
I've been using this plugin for over a year now and it's spectacular!
But I have a question to see if you can answer me.
There is an option in EssentialsX that allows you to change the player's nickname within the server, but since LPC is on, it doesn't change the player's nickname.
Would there be a way to see the nicknames assigned by EssentialX in the chat?

"TIP: EssentialsX Commands /nick Jimmy"
Thanks!

**Comment by BukkitSmurf** [comment]
Hey, have you tried putting {displayname} placeholder instead of {name} placeholder in config.yml of LPC?

**Comment by Arthuuurr** [comment]
It didn't work for me. Do I have to install some PlaceholderAPI variable?
https://cdn.discordapp.com/attachments/950482391649099836/950849103384965210/unknown.png

**Comment by BukkitSmurf** [comment]
What version are you? Please install the latest LPC version - 3.5.0.

**Comment by Arthuuurr** [comment]
Ok, it worked for me. What I was missing was the version.
Thank you very much for the support!

**Comment by BukkitSmurf** [comment]
Great!
