### ISSUE TITLE
LPC for paper

### ISSUE THREAD

**Issue by mastermc05** [BukkitSmurf/LPC#16]
Even if it works great on paper, it doesn't use it's possibilities, so maybe you could make another plugin, with the same functionality, which uses minimessages, and maybe other paper api
like there already are people who would like to see hover texts in their prefixes, and other
since your plugin tends to be extremely small and lightweight, i don't think it's worth to make that plugin support both

**Comment by BukkitSmurf** [comment]
Hey, I'm already preparing a new plugin for the chat format. It will use MiniMessage and Hover/Clickable texts. I totally agree with you that this shouldn't be an LPC update and I plan to make this new resource premium. I would like to give it to you for free when it's launched as this will be a pilot project. Please contact me on Discord: BukkitSmurf#3388 and let me know what you think.
